export const PRODUCT_ADDED_TO_CATALOG = 'PRODUCT_ADDED_TO_CATALOG';
export const PRODUCT_REMOVE_FROM_CATALOG = 'PRODUCT_REMOVE_FROM_CATALOG';
export const ALL_PRODUCTS_REMOVE_FROM_CATALOG = 'ALL_PRODUCTS_REMOVE_FROM_CATALOG';
